server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shinhan
#    url : jdbc:h2:./shinhan
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

jwt:
  password: testPasswordtestPasswordtestPasswordtestPasswordtestPasswordtestPassword!testPassword


cloud:
  aws:
    s3:
      bucket: eggmoneynabucket
    credentials:
      access-key: AKIA6NLZ7AA63MGKRUQ3
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
