server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.95.36:3306/eggmoneyna
    username: root
    password: 12341234
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/shinhan
##    url : jdbc:h2:./shinhan
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  main:
#    allow-circular-references: true
#
#  profiles:
#    include: db

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

jwt:
  password: ENC(Bjl3aK5QCSk0QT6VXnQsptV3v8DTNqxtTcvDxggQkbZZLj83+rHFRFQFWTaP37iR+eYRFNqJn9dsAqM/E8T/Qc+flLyRp3VgfnSAXJe4zdyYepxRbf0KqoGtQqYdwPFx)


cloud:
  aws:
    s3:
      bucket: ENC(8d+zFkIbnxlpZiUeixqgJXVH4J5dDSdOa67zuxqmCCc=)
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
